spring.application.name=SpringEcomBackend

#Local PostgreSQL database configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/ecom-db
#Docker PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/ecom-db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

# Set max file size for single file upload (e.g., 100MB)
spring.servlet.multipart.max-file-size=100MB
# Set max request size for total upload (e.g., multiple files in a single request)
spring.servlet.multipart.max-request-size=100MB

spring.ai.model.chat=anthropic
spring.ai.model.image=openai
spring.ai.model.embedding=ollama

#spring.ai.anthropic.base-url=api.anthropic.com #Not required or set it with http or https
spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
spring.ai.anthropic.chat.options.model=claude-haiku-4-5
#https://docs.spring.io/spring-ai/reference/api/chat/anthropic-chat.html

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4.1-mini
spring.ai.openai.image.options.model=gpt-image-1
spring.ai.openai.embedding.enabled=false

ollama.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
ollama.embed-model=${OLLAMA_EMBED_MODEL:nomic-embed-text}
#DISABLE OPENAI EMBEDDING - if you want to use ollama embedding instead of openai embedding
spring.ai.ollama.embedding.enabled=true

#Vector store properties - below set to false because docker-compose has its own init.sql script to create the pgvector extension and table
spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:init/schema.sql
spring.ai.vectorstore.pgvector.initialize-schema=false